### PR TITLE
 Adding custom Externals / Resolver

### PR DESCRIPTION
**Pull request by ZER0**

### CODE REVIEW

**Review by CPerezz — CHANGES_REQUESTED** [review]
Could you remove `module_examples/modules/counter/counter.wasm`, ` module_examples/modules/panic/panic.wasm` and ` module_examples/modules/resolver/resolver.wasm`? I don't think it makes sense to have them in the repo. We can always compile them locally.

**Comment by krl** [comment]
Yeah, that would make sense. We could add wasm files to .gitignore

**Comment by ZER0** [comment]
> Could you remove `module_examples/modules/counter/counter.wasm`, ` module_examples/modules/panic/panic.wasm` and ` module_examples/modules/resolver/resolver.wasm`? I don't think it makes sense to have them in the repo. We can always compile them locally.

I actually did that already. Probably it went lost in one of the updates. I will re-add it.

**Comment by ZER0** [comment]
> > Could you remove `module_examples/modules/counter/counter.wasm`, ` module_examples/modules/panic/panic.wasm` and ` module_examples/modules/resolver/resolver.wasm`? I don't think it makes sense to have them in the repo. We can always compile them locally.
> 
> I actually did that already. Shouldn't be that in master?

Yes, it is:
https://github.com/dusk-network/canonical/commit/bbeb85a523c392da97ace163a144db7efbdb7c2a

**Review by krl — APPROVED** [review]
lgtm!

**Review by CPerezz — APPROVED** [review]
LGTM

**Pull request merged**
